language: rust

os:
  - linux
  - windows

rust:
  - stable
  - beta
  - nightly

git:
  depth: 1

cache: cargo

matrix:
  allow_failures:
    - os: windows

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
