[package]
name = "qni-connector-ws-rs"
version = "0.2.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[features]
default = []
ssl = ["ws/ssl", "openssl"]

[dependencies.qni-core-rs]
git = "https://github.com/Riey/qni-core-rs"

[dependencies.ws]
version = "*"

[dependencies.openssl]
version = "0.10"
optional = true

[dependencies]
simple-error = "*"
cfg-if = "*"
