[package]
name = "qni-connector-ws-rs"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[features]
default = []
ssl = ["ws/ssl", "openssl"]

[dependencies.qni-core-rs]
git = "https://github.com/Riey/qni-core-rs"

[dependencies.ws]
git = "https://github.com/peddermaster2/ws-rs"
rev = "fac799e61a70af06c71443138ef5601dd290dc15"

[dependencies.openssl]
version = "0.10"
optional = true

[dependencies]
simple-error = "*"
cfg-if = "*"
